//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Education
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public string Subtitle1 { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public string Subtitle2 { get; set; }

        [Range(0.00, 4.00, ErrorMessage = "Lütfen 0.00 ile 4.00 arasýnda bir deðer giriniz.")]
        public string GPA { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public string Date { get; set; }
    }
}
