//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Admin
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "Bu alan boþ býrakýlamaz.")]
        [StringLength(10, MinimumLength = 6, ErrorMessage = "Þifre en az 6 karakter olmalýdýr.")]
        public string Password { get; set; }
    }
}
